<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Friflo.Vectorization.WebGPU</AssemblyName>
        <RootNamespace>Friflo.Vectorization.WebGPU</RootNamespace>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <ItemGroup>
      <!-- Für den lokalen Build & Tests: Kopiert die DLLs in den bin-Ordner -->
      <None Include="..\runtimes\**\*.*">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <Link>runtimes\%(RecursiveDir)%(Filename)%(Extension)</Link>
        <!-- WICHTIG für NuGet: Packt die Dateien an die richtige Stelle im .nupkg -->
        <PackagePath>runtimes\</PackagePath>
        <Pack>true</Pack>
      </None>
    </ItemGroup>

</Project>
